version: '3'
services:
  php1:
    build: .
    container_name: php1
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./config/db_docker.php:/app/config/db.php:delegated
    networks:
      - yea_net
    ports:
      - '8001:80'
    depends_on:
      - mysql
  php2:
    build: .
    container_name: php2
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./config/db_docker.php:/app/config/db.php:delegated
    networks:
      - yea_net
    ports:
      - '8002:80'
    depends_on:
      - mysql
  mysql:
    image: "mysql:5.7.22"
    container_name: mysql
    volumes:
      - yea_mysql_data:/var/lib/mysql
    networks:
      - yea_net
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root

volumes:
  yea_mysql_data:

networks:
  yea_net:
    driver: bridge



